var tree = [["Eloquent",,"",
                [["Enumeration","Eloquent\/Enumeration.html","",
                [["Exception","Eloquent\/Enumeration\/Exception.html","",
                [["AbstractUndefinedMemberException","Eloquent\/Enumeration\/Exception\/AbstractUndefinedMemberException.html"," < Exception",
                [        ]],["ExtendsConcreteException","Eloquent\/Enumeration\/Exception\/ExtendsConcreteException.html"," < Exception",
                [        ]],["UndefinedMemberException","Eloquent\/Enumeration\/Exception\/UndefinedMemberException.html"," < AbstractUndefinedMemberException",
                [        ]],["UndefinedMemberExceptionInterface","Eloquent\/Enumeration\/Exception\/UndefinedMemberExceptionInterface.html","",
                [        ]]        ]],["AbstractEnumeration","Eloquent\/Enumeration\/AbstractEnumeration.html"," < AbstractValueMultiton",
                [        ]],["AbstractMultiton","Eloquent\/Enumeration\/AbstractMultiton.html","",
                [        ]],["AbstractValueMultiton","Eloquent\/Enumeration\/AbstractValueMultiton.html"," < AbstractMultiton",
                [        ]],["EnumerationInterface","Eloquent\/Enumeration\/EnumerationInterface.html","",
                [        ]],["MultitonInterface","Eloquent\/Enumeration\/MultitonInterface.html","",
                [        ]],["ValueMultitonInterface","Eloquent\/Enumeration\/ValueMultitonInterface.html","",
                [        ]]        ]]        ]]        ]

